### ISSUE TITLE
something wrong with the BatchNorm of self.fc layer 

### ISSUE THREAD

**Issue by songkq** [rcdaudt/patch_based_change_detection#1]
Thank you for sharing your code.
Maybe you should replace the **nn.BatchNorm2d** with the **nn.BatchNorm1d** in the self.fc layer.
Or it will raise the ValueError: expected 4D input (got 2D input) when running forward.

**Comment by rcdaudt** [comment]
Thanks for the heads up! This didn't use to be an issue with older versions of PyTorch. It's fixed now.
