### ISSUE TITLE
Details about the dataset and code

### ISSUE THREAD

**Issue by Daisy-7** [rcdaudt/patch_based_change_detection#2]
Thanks for sharing!
How did the dataset get the patch of 15×15? I have read the paper, but the number of training sets is not described in detail.The operation process of obtaining the change of the whole image mentioned in the paper is also not very clear. Could you share more about them?
 I'm new to deep learning and don't know much about it. It would be better if you could share more code and details.

**Comment by zhengxinvip** [comment]
I have the same question with you. @rcdaudt  can you share more details about the code,  thanks you very much.

**Comment by zhengxinvip** [comment]
> Thanks for sharing!
> How did the dataset get the patch of 15×15? I have read the paper, but the number of training sets is not described in detail.The operation process of obtaining the change of the whole image mentioned in the paper is also not very clear. Could you share more about them?
> I'm new to deep learning and don't know much about it. It would be better if you could share more code and details.

have you solve the problem

**Comment by zhengxinvip** [comment]
> Thanks for sharing!
> How did the dataset get the patch of 15×15? I have read the paper, but the number of training sets is not described in detail.The operation process of obtaining the change of the whole image mentioned in the paper is also not very clear. Could you share more about them?
> I'm new to deep learning and don't know much about it. It would be better if you could share more code and details.

I have the same question. have you solve it?

**Comment by CESI2Jaafar** [comment]
Hey bro
Could you use it and runned?

**Comment by rcdaudt** [comment]
Hi, I recommend that you check the repository for the fully convolutional approach: https://github.com/rcdaudt/fully_convolutional_change_detection

The patch-based approach in this repo is more costly to run and produces worse results.
